/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Demand (
  additionalType: Option[String],
  alternateName: Option[String],
  description: Option[String],
  disambiguatingDescription: Option[String],
  image: Option[String],
  mainEntityOfPage: Option[String],
  name: Option[String],
  potentialAction: Option[Any],
  url: Option[String],
  acceptedPaymentMethod: Option[Any],
  advanceBookingRequirement: Option[Any],
  areaServed: Option[Any],
  availability: Option[Any],
  availabilityEnds: Option[String],
  availabilityStarts: Option[String],
  availableAtOrFrom: Option[String],
  availableDeliveryMethod: Option[Any],
  businessFunction: Option[Any],
  deliveryLeadTime: Option[Any],
  eligibleCustomerType: Option[Any],
  eligibleDuration: Option[Any],
  eligibleQuantity: Option[Any],
  eligibleRegion: Option[Any],
  eligibleTransactionVolume: Option[Any],
  gtin12: Option[String],
  gtin13: Option[String],
  gtin14: Option[String],
  gtin8: Option[String],
  includesjson: Option[Any],
  ineligibleRegion: Option[Any],
  inventoryLevel: Option[Any],
  itemCondition: Option[Any],
  itemOffered: Option[Any],
  mpn: Option[Any],
  priceSpecification: Option[Any],
  seller: Option[Any],
  seeker: Option[Seq[Any]],
  serialNumber: Option[String],
  sku: Option[String],
  validFrom: Option[String],
  validThrough: Option[String],
  warranty: Option[Any],
  role: Option[Seq[Any]]
) extends ApiModel


