/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class NGO (
  additionalType: Option[String],
  alternateName: Option[String],
  description: Option[String],
  disambiguatingDescription: Option[String],
  image: Option[String],
  mainEntityOfPage: Option[String],
  name: Option[String],
  potentialAction: Option[Any],
  url: Option[String],
  address: Option[Any],
  aggregateRating: Option[Any],
  alumni: Option[Any],
  areaServed: Option[Any],
  award: Option[String],
  brand: Option[Any],
  contactPoint: Option[Any],
  department: Option[Any],
  dissolutionDate: Option[Any],
  duns: Option[String],
  email: Option[String],
  employee: Option[Any],
  events: Option[Seq[Any]],
  faxNumber: Option[String],
  founder: Option[Any],
  foundingDate: Option[String],
  foundingLocation: Option[Any],
  funder: Option[Any],
  globalLocationNumber: Option[String],
  hasOfferCatalog: Option[Any],
  hasPOS: Option[Any],
  isicV4: Option[String],
  legalName: Option[String],
  leiCode: Option[String],
  location: Option[Any],
  logo: Option[String],
  makesOffer: Option[Seq[Any]],
  member: Option[Seq[Any]],
  memberOf: Option[Any],
  naics: Option[String],
  numberOfEmployees: Option[Int],
  owns: Option[Any],
  parentOrganization: Option[Any],
  review: Option[Any],
  seeks: Option[Any],
  sponsor: Option[Any],
  subOrganization: Option[Any],
  taxID: Option[String],
  telephone: Option[String],
  vatID: Option[String],
  complete: Option[Boolean]
) extends ApiModel


